#!/bin/bash

win_setup() {
    cmd() {
        if [[ -f /mnt/c/Windows/System32/cmd.exe ]]; then
            eval /mnt/c/Windows/System32/cmd.exe /C $@
        else
            echo "Cannot find cmd.exe" >&2
        fi
    }

    subl='"C:\Users\nelson\AppData\Roaming\Sublime Text 3\Packages"'
    repo='"C:\Users\nelson\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs\home\nelson\.dot\sublime\Packages"'

    cmd "rmdir /S /Q $subl" 2>/dev/null
    cmd "mklink /D $subl $repo"
}

winSubl="/mnt/c/Users/nelson/AppData/Roaming/Sublime Text 3"
cmderSubl="$HOME/"  # TODO
linuxSubl="$HOME/.config/sublime-text-3"
repo="$(cd "$(dirname $0)"; pwd)/Packages"
if [[ -d $winSubl ]]; then
    win_setup
    exit
elif [[ -d $cmderSubl ]]; then
    # TODO
    echo "TODO" >&2
    exit 1
elif [[ -d $linuxSubl ]]; then
    subl="$linuxSubl"
else
    echo "Sublime directory not found" >&2
    exit 1
fi
subl="${subl}/Packages"

# TODO: test
rm -rf "$subl"
ln -fs "$repo" "$subl"
