#!/bin/bash

linuxSubl="$HOME/.config/sublime-text-3"
macSubl="$HOME/Library/Application Support/Sublime Text 3"
winSubl="$HOME/AppData/Roaming/Sublime Text 3"
repo="$HOME"
if [[ -d $linuxSubl ]]; then
    subl="$linuxSubl"
elif [[ -d $macSubl ]]; then
    subl="$macSubl"
elif [[ -d $winSubl ]]; then
    subl="$winSubl"
    if [[ ! -z $CMDER_ROOT ]]; then
    	repo="$CMDER_ROOT/../.."
    fi
else
    echo "No Sublime directory found"
    exit 1
fi
subl="${subl}/Packages"
repo="${repo}/Projects/Git/config-files/Sublime/Packages"

cd "$repo"
packages=(*)
for package in "${packages[@]}"; do
    if [[ $package == User ]]; then
        mkdir -p User && cd User
        userFiles=(*)
        for file in "${userFiles[@]}"; do
            ln -Fs "${repo}/User/$file" "${subl}/User"
        done
    else
        ln -Fs "${repo}/$package" "$subl"
    fi
done

