#!/bin/bash
# 



s_help() {
    echo 'Usage: s [-h|--help]'
    echo
    echo 'Short description.'
    echo
    echo 'Long, multi-line description.'
    echo
    echo 'Options:'
    echo '  -h, --help  Print this help message and exit'
    exit
}



s_err() {
    [[ "$1" == help ]] &&
        s_help >&2

    echo "s: $1" >&2
    exit 1
}



s() {
    [[ $# == 0 ]] &&
        s_err help

    # Parse arguments
    local help
    while [[ $# > 0 ]]; do
        case $1 in
            -h|--help)
                help=1 ;;
            -*|--*)
                s_err "option not recognized: $1" ;;
            *)
                s_err "argument not recognized: $1" ;;
        esac
        shift
    done

    [[ "$help" == 1 ]] &&
        s_help

}



s "$@"
