; vim:ft=dosini

[module/i3]
type = internal/i3
format = <label-state> <label-mode>
index-sort = true
wrapping-scroll = false

; Only show workspaces on the same output as the bar
pin-workspaces = true

; ws-icon-[0-9] = <full-i3-ws-name>;<icon>
ws-icon-0 = 1:;
ws-icon-1 = 2:;
ws-icon-2 = 3:3;3
ws-icon-3 = 4:4;4
ws-icon-4 = 5:5;5
ws-icon-5 = 6:6;6
ws-icon-6 = 7:7;7
ws-icon-7 = 8:;
ws-icon-8 = 9:;
ws-icon-9 = 10:10;10

label-mode-padding = 2
label-mode-foreground = #000
label-mode-background = ${colors.primary}

; focused = Active workspace on focused monitor
label-focused = %icon%
label-focused-background = ${colors.background-alt}
label-focused-underline = ${colors.primary}
label-focused-padding = 2

; unfocused = Inactive workspace on any monitor
label-unfocused = %icon%
label-unfocused-padding = ${self.label-focused-padding}

; visible = Active workspace on unfocused monitor
label-visible = %icon%
label-visible-background = ${self.label-focused-background}
label-visible-underline = ${self.label-focused-underline}
label-visible-padding = ${self.label-focused-padding}

; urgent = Workspace with urgency hint set
label-urgent = %icon%
label-urgent-background = ${colors.alert}
label-urgent-padding = ${self.label-focused-padding}
