#!/bin/bash
# dimmer -- incrementally lowers screen brightness then turns off the display.
# Behaves like `xset dpms force off` in that any user input restores the screen
# brightness to how it was before.


# Value to lower the brightness to
min_brightness=0

# The -time and -steps flags for xbacklight
fade_time=400
fade_steps=20

# Time between each screen fade step
fade_step_time=0.02


get_brightness()  { xbacklight -get; }
set_brightness()  { xbacklight -steps 1 -set $1; }
fade_brightness() { xbacklight -time $fade_time -steps $fade_steps -set $1; }


trap "set_brightness $(get_brightness)" EXIT TERM INT

fade_brightness $min_brightness
xset dpms force off
