#!/bin/bash

dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify \
    /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get \
    string:org.mpris.MediaPlayer2.Player string:Metadata |
    sed -n '/artist/{n;n;p}; /title/{n;p}' |
    cut -d '"' -sf 2,3 |
    tr -d '"' |
    sed "N;s/\n/ - /"
