"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

format = """
$username\
${custom.username_hostname_seperator}\
$hostname\
$localip\
$directory\
$git_branch\
$git_state\
$git_status\
\n\
$character\
"""

# $package\
right_format = """
$c\
$cmake\
$rust\
$battery\
$time\
"""

[battery]
disabled = false
display = [{ threshold = 40 }]

[custom.username_hostname_seperator]
when = '[ -n "${SSH_CONNECTION}${SSH_CLIENT}${SSH_TTY}" ]'
format = '@'
ignore_timeout = true

[c]
format = 'via [$name $version]($style)'
detect_extensions = ['c', 'h']

[directory]
truncation_length = 6
truncate_to_repo = true

[git_status]
ahead = '↑${count}'
behind = '↓${count}'
diverged = '↓${behind_count}↑${ahead_count}'
format = '([\[$all_status$ahead_behind\]]($style) )'

[hostname]
ssh_only = true
format = '[$hostname]($style) '

[localip]
disabled = false
ssh_only = true
format = '\([$localipv4]($style)\) '

[time]
disabled = false
format = ' [$time]($style) '
style = 'fg:242'
use_12hr = true

[username]
show_always = false
format = '[$user]($style)'
