#!/bin/bash

# <git dir>/hooks
hooks="$(dirname "$0")"

# Url of reciever of the push
url="$2"

# Hash of last commit on remote
remote_commit=$(git ls-remote "$url" | grep HEAD | awk '{print $1}')

# Hash of last local commit
current_commit=$(git rev-parse HEAD)


# Compile added, modified, and uncompiled bin-src/ files
"${hooks}/cpp-compile.sh" pre-push "$remote_commit" "$current_commit"


# Update plugins if changes were made in plugin section of files/.vimrc
"${hooks}/update-vim-plugins.sh"
